version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2228:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9192:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CREATE_TOPICS: "sv-uploads-test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "${MY_IP}"
      KAFKA_ADVERTISED_PORT: 9192

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
