version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2228:2181"
    networks:
      - eventsgateway
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9192:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CREATE_TOPICS: "sv-uploads-test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "${MY_IP}"
      KAFKA_ADVERTISED_PORT: 9192
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - eventsgateway
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
      - '8050:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - '/private/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - eventsgateway
  gobblin:
    image: 797740695898.dkr.ecr.us-east-1.amazonaws.com/gobblin:v0.14.0-custom
    volumes:
      - ./gobblin/conf:/etc/opt/job-conf
      - ./gobblin/work-dir:/home/gobblin/work-dir
      - ./gobblin/logs:/var/log/gobblin
      - ./gobblin/gobblin-standalone.properties:/opt/gobblin/gobblin-dist/conf/gobblin-standalone.properties
      - ./gobblin/log4j-config.xml:/home/gobblin/log4j-config.xml
    depends_on:
      - "kafka"
      - "localstack"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      S3_ENDPOINT: "http://localstack:4572"
      S3_BUCKET: "eventsgateway-local"
      LOG_LEVEL: "DEBUG"
      GOBBLIN_PUBLISHER_PATH: "/output"
      FWDIR_LIB: "/opt/gobblin/gobblin-dist/lib"
    networks:
      - eventsgateway
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    ports:
      - '8888:8888'
    volumes:
      - ./pyspark-notebook/work:/home/jovyan/work
    networks:
      - eventsgateway

networks:
  eventsgateway: 
    external:
      name: eventsgateway
