extensions:
  kafkaproducer:
    brokers: localhost:9192
    maxMessageBytes: 3000000
client:
  async: false
  channelBuffer: 500
  lingerInterval: 500ms
  batchSize: 50
  kafkatopic: default-topic
  maxRetries: 3
  numRoutines: 5
  retryInterval: 1s
  grpc:
    serverAddress: localhost:5000
    timeout: 500ms
loadtestclient:
  randSleepCeilingMs: 500
  duration: 10s
  propsSize: small # small, medium, large, jumbo
sentry:
  url: ""
newrelic:
  app: "eventsgateway"
  key: ""
