extensions:
  kafkaproducer:
    brokers: localhost:9192
    maxMessageBytes: 3000000
client:
  grpc:
    serveraddress: localhost:8888
    timeoutms: 500
  kafkatopic: default-topic
sentry:
  url: ""
newrelic:
  app: "eventsgateway"
  key: ""
