extensions:
  kafkaproducer:
    brokers: localhost:9192
    maxMessageBytes: 3000000
client:
  async: false
  channelBuffer: 500
  lingerInterval: 500ms
  batchSize: 10
  kafkatopic: default-topic
  maxRetries: 3
  numRoutines: 2
  retryInterval: 1s
  grpc:
    serverAddress: localhost:5000
    timeout: 500ms
loadtestclient:
  duration: 10s
  threads: 2
  randSleepCeilingMs: 500
  randPropsSize: small # small, medium, large, jumbo
sentry:
  url: ""
newrelic:
  app: "eventsgateway"
  key: ""
