jaeger:
  disabled: true
  samplingProbability: 0.1
  serviceName: events-gateway
extensions:
  kafkaproducer:
    timeout: 250ms
    brokers: localhost:9192
    maxMessageBytes: 1000000
    net:
      maxOpenRequests: 100
    retry:
      max: 0
server:
  maxConnectionIdle: 20s
  maxConnectionAge: 20s
  maxConnectionAgeGrace: 5s
  Time: 10s
  Timeout: 500ms
client:
  async: false
  channelBuffer: 500
  lingerInterval: 500ms
  batchSize: 10
  kafkatopic: default-topic
  maxRetries: 3
  numRoutines: 2
  retryInterval: 2s
  grpc:
    serverAddress: localhost:5000
    timeout: 500ms
loadtestclient:
  duration: 10s
  threads: 2
  randSleepCeilingMs: 500
  randPropsSize: small # small, medium, large, jumbo
sentry:
  url: ""
newrelic:
  app: "eventsgateway"
  key: ""
