extensions:
  kafkaproducer:
    brokers: localhost:9192
    maxMessageBytes: 3000000
client:
  async: false
  channelBuffer: 500
  flushInterval: 1s
  flushSize: 1
  kafkatopic: default-topic
  maxRetries: 3
  numRoutines: 1
  retryInterval: 1s
  grpc:
    serveraddress: localhost:5000
    timeoutms: 500ms
sentry:
  url: ""
newrelic:
  app: "eventsgateway"
  key: ""
